### ISSUE TITLE
[FEATURE] Native authentication support for GitHub Actions using the OpenID Connect from Azure

### ISSUE THREAD

**Issue by nfx** [databricks/databricks-sdk-py#383]
**Problem Statement**

Azure & GitHub work very well together: https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure and we pickup that as `auth_type=azure-cli`:

![image](https://github.com/databricks/databricks-sdk-py/assets/259697/08edeea7-1d8e-4198-932e-9f8eb2d1fe9f)

but it does require installing additional action and passing additional secrets, like `ARM_SUBSCRIPTION_ID` and `ARM_TENANT_ID` and `ARM_CLIENT_ID`. 

```
     - uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
```

**Proposed Solution**
Ideally, we have to detect github actions environment and use just `DATABRICKS_HOST` and `ARM_CLIENT_ID` environment variables.

**Additional Context**
This would only work for Azure now.
